In [17]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [18]:
from sklearn import datasets

In [19]:
boston = pd.read_csv('BostonHousing.csv')

In [20]:
boston.head(2)

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.9,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.9,9.14,21.6

In [22]:
boston = boston.drop(columns='medv')

In [23]:
boston.head(2)

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.9,4.98
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.9,9.14

In [34]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score

In [35]:
boston.iloc[:,0:-1]

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90
...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90

In [27]:
from sklearn.model_selection import train_test_split as tts
X_train,X_test,y_train,y_test=tts(boston.iloc[:,0:-1], boston.iloc[:,-1],
                                 test_size=0.2, random_state=123)

In [36]:
X_train.shape

(404, 12)

In [37]:
X_test.shape

(102, 12)

In [38]:
y_train.shape

(404,)

In [39]:
y_test.shape

(102,)

In [40]:
lr = LinearRegression()
dt = DecisionTreeRegressor()
knn = KNeighborsRegressor()

In [41]:
lr.fit(X_train,y_train)
dt.fit(X_train,y_train)
knn.fit(X_train,y_train)

KNeighborsRegressor()

In [42]:
y_pred1 = lr.predict(X_test)
y_pred2 = dt.predict(X_test)
y_pred3 = knn.predict(X_test)

In [43]:
print("For Linear Regression: ", r2_score(y_pred1, y_test))
print("For Decision Trees: ", r2_score(y_pred2, y_test))
print("For KNN : ", r2_score(y_pred3, y_test))

For Linear Regression:  0.3767700395643453
For Decision Trees:  0.5533716538905809
For KNN :  -0.08261625434915199

In [44]:
from sklearn.ensemble import BaggingRegressor

In [45]:
bag_regressor = BaggingRegressor(random_state=1)
bag_regressor.fit(X_train,y_train)

BaggingRegressor(random_state=1)

In [46]:
y_preds = bag_regressor.predict(X_test)

In [47]:
print("Train Coeff : ", bag_regressor.score(X_train,y_train))
print("Test Coeff : ", bag_regressor.score(X_test,y_test))

Train Coeff :  0.9493798870862624
Test Coeff :  0.6634298285108977

In [60]:
params = {
    'estimator':['LinearRegression()', KNeighborsRegressor(),
                     DecisionTreeRegressor()],
    'n_estimators' : [20,50,100],
    'max_samples' : [0.5, 1.0],
    'max_features' : [0.5,1.0],
    'bootstrap' : [True, False],
    'bootstrap_features' : [True, False]
}

In [61]:
bag_grid = GridSearchCV(BaggingRegressor(random_state=1,n_jobs=-1),
                       param_grid=params,
                       cv=3,
                       n_jobs=-1,
                       verbose=1)

In [62]:
bag_grid.fit(X_train,y_train)

Fitting 3 folds for each of 144 candidates, totalling 432 fits

C:\Users\dell\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:540: FitFailedWarning:
144 fits failed out of a total of 432.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
144 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\dell\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\dell\anaconda3\Lib\site-packages\sklearn\utils\validation.py", line 66, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\anaconda3\Lib\site-packages\sklearn\base.py", line 1466, in wrapper
    estimator._validate_params()
  File "C:\Users\dell\anaconda3\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\dell\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'estimator' parameter of BaggingRegressor must be an object implementing 'fit' and 'predict' or None. Got 'LinearRegression()' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\dell\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1103: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.54706187 0.57334596 0.56981854 0.56915108 0.59663924 0.59749943
 0.53891502 0.54671017 0.54456635 0.56212179 0.56989881 0.57022178
 0.65980593 0.68044709 0.68273807 0.67716271 0.68921262 0.69028111
 0.65588662 0.67897077 0.69190843 0.69324639 0.70303939 0.70730807
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.57330946 0.56940039 0.56496306 0.60248314 0.59321394 0.59024059
 0.50168616 0.50915374 0.51152236 0.51869532 0.51798981 0.52275546
 0.67393395 0.68867638 0.68996629 0.67917257 0.68539045 0.70020746
 0.68575563 0.70025535 0.70774228 0.6950421  0.71234122 0.71090856
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.55602758 0.56898967 0.57085883 0.58374413 0.60479034 0.60432804
 0.5394379  0.5482434  0.54808796 0.56726873 0.57867298 0.57789333
 0.66654597 0.6747729  0.68522052 0.66965348 0.6829774  0.68715
 0.68682975 0.69511357 0.70552664 0.69017021 0.69615538 0.69481557
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.56515002 0.56574135 0.5643682  0.60632144 0.60045355 0.59636288
 0.51301572 0.51134573 0.50879034 0.51518095 0.51518095 0.51518095
 0.6842218  0.68630978 0.69187669 0.66942227 0.6896239  0.69444955
 0.68474566 0.6939718  0.70096927 0.42979239 0.43665855 0.44376593]
  warnings.warn(

GridSearchCV(cv=3, estimator=BaggingRegressor(n_jobs=-1, random_state=1),
             n_jobs=-1,
             param_grid={'bootstrap': [True, False],
                         'bootstrap_features': [True, False],
                         'estimator': ['LinearRegression()',
                                       KNeighborsRegressor(),
                                       DecisionTreeRegressor()],
                         'max_features': [0.5, 1.0], 'max_samples': [0.5, 1.0],
                         'n_estimators': [20, 50, 100]},
             verbose=1)

In [67]:
print('Train R^2 Score : %.3f'%bag_grid.best_estimator_.score(X_train, y_train))
print('Test R^2 Score : %.3f'%bag_grid.best_estimator_.score(X_test, y_test))
print('Best R^2 Score Through Grid Search : %.3f'%bag_grid.best_score_)
print('Best Parameters : ',bag_grid.best_params_)

Train R^2 Score : 0.962
Test R^2 Score : 0.678
Best R^2 Score Through Grid Search : 0.712
Best Parameters :  {'bootstrap': True, 'bootstrap_features': False, 'estimator': DecisionTreeRegressor(), 'max_features': 1.0, 'max_samples': 1.0, 'n_estimators': 50}