In [1]:
import numpy as np
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
from sklearn.compose import ColumnTransformer

In [3]:
df = pd.read_csv('covid_toy.csv')

In [4]:
df.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [5]:
df.shape

(100, 6)

In [6]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [7]:
from sklearn.impute import SimpleImputer

In [12]:
from sklearn.preprocessing import OrdinalEncoder

In [13]:
from sklearn.preprocessing import OneHotEncoder

In [8]:
si = SimpleImputer(strategy='median')

In [11]:
df.head(3)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes
2   42   Male  101.0  Mild    Delhi        No

In [21]:
trf = ColumnTransformer([
    ('trf1', SimpleImputer(strategy='median'), ['fever']),
    ('trf2', OrdinalEncoder(categories=[['Mild','Strong']]), ['cough']),
    ('trf3', OneHotEncoder(sparse_output=False, drop='first'), ['gender', 'city'])
], remainder='passthrough')

In [23]:
df_trf=trf.fit_transform(df)

In [25]:
df_trf

array([[103.0, 0.0, 1.0, 0.0, 1.0, 0.0, 60, 'No'],
       [100.0, 0.0, 1.0, 1.0, 0.0, 0.0, 27, 'Yes'],
       [101.0, 0.0, 1.0, 1.0, 0.0, 0.0, 42, 'No'],
       [98.0, 0.0, 0.0, 0.0, 1.0, 0.0, 31, 'No'],
       [101.0, 0.0, 0.0, 0.0, 0.0, 1.0, 65, 'No'],
       [101.0, 0.0, 0.0, 0.0, 0.0, 0.0, 84, 'Yes'],
       [101.0, 1.0, 1.0, 0.0, 0.0, 0.0, 14, 'No'],
       [101.0, 1.0, 0.0, 0.0, 0.0, 1.0, 20, 'Yes'],
       [100.0, 1.0, 0.0, 0.0, 0.0, 0.0, 19, 'No'],
       [101.0, 0.0, 0.0, 1.0, 0.0, 0.0, 64, 'No'],
       [101.0, 0.0, 0.0, 1.0, 0.0, 0.0, 75, 'No'],
       [98.0, 0.0, 0.0, 0.0, 0.0, 1.0, 65, 'Yes'],
       [99.0, 1.0, 0.0, 0.0, 1.0, 0.0, 25, 'No'],
       [102.0, 0.0, 1.0, 0.0, 0.0, 0.0, 64, 'Yes'],
       [104.0, 0.0, 1.0, 0.0, 0.0, 0.0, 51, 'No'],
       [103.0, 1.0, 1.0, 0.0, 1.0, 0.0, 70, 'Yes'],
       [103.0, 0.0, 0.0, 0.0, 1.0, 0.0, 69, 'Yes'],
       [98.0, 1.0, 0.0, 1.0, 0.0, 0.0, 40, 'No'],
       [98.0, 0.0, 0.0, 0.0, 0.0, 0.0, 64, 'Yes'],
       [101.0, 1.0, 0.0, 0.0, 0.0, 0.0, 42, 'Yes'],
       [98.0, 1.0, 1.0, 0.0, 0.0, 0.0, 12, 'No'],
       [98.0, 0.0, 1.0, 0.0, 0.0, 0.0, 73, 'Yes'],
       [98.0, 1.0, 0.0, 0.0, 1.0, 0.0, 71, 'Yes'],
       [98.0, 0.0, 0.0, 1.0, 0.0, 0.0, 80, 'Yes'],
       [100.0, 1.0, 0.0, 0.0, 1.0, 0.0, 13, 'No'],
       [101.0, 0.0, 1.0, 0.0, 0.0, 1.0, 23, 'No'],
       [100.0, 0.0, 0.0, 0.0, 1.0, 0.0, 19, 'Yes'],
       [102.0, 1.0, 0.0, 1.0, 0.0, 0.0, 33, 'No'],
       [104.0, 0.0, 1.0, 0.0, 1.0, 0.0, 16, 'No'],
       [101.0, 1.0, 0.0, 0.0, 0.0, 1.0, 34, 'Yes'],
       [101.0, 0.0, 1.0, 1.0, 0.0, 0.0, 15, 'Yes'],
       [103.0, 0.0, 1.0, 0.0, 1.0, 0.0, 83, 'No'],
       [101.0, 1.0, 0.0, 1.0, 0.0, 0.0, 34, 'Yes'],
       [98.0, 0.0, 0.0, 0.0, 1.0, 0.0, 26, 'No'],
       [102.0, 0.0, 1.0, 0.0, 0.0, 1.0, 74, 'Yes'],
       [102.0, 1.0, 0.0, 0.0, 0.0, 0.0, 82, 'No'],
       [101.0, 0.0, 0.0, 0.0, 0.0, 0.0, 38, 'No'],
       [100.0, 0.0, 1.0, 0.0, 1.0, 0.0, 55, 'No'],
       [101.0, 0.0, 0.0, 1.0, 0.0, 0.0, 49, 'Yes'],
       [103.0, 0.0, 0.0, 0.0, 1.0, 0.0, 50, 'No'],
       [102.0, 0.0, 0.0, 1.0, 0.0, 0.0, 49, 'No'],
       [101.0, 0.0, 1.0, 0.0, 1.0, 0.0, 82, 'Yes'],
       [100.0, 0.0, 1.0, 1.0, 0.0, 0.0, 27, 'Yes'],
       [99.0, 0.0, 0.0, 0.0, 0.0, 0.0, 22, 'Yes'],
       [102.0, 1.0, 1.0, 1.0, 0.0, 0.0, 20, 'No'],
       [99.0, 0.0, 1.0, 0.0, 0.0, 0.0, 72, 'No'],
       [101.0, 0.0, 0.0, 0.0, 0.0, 1.0, 19, 'No'],
       [104.0, 0.0, 0.0, 0.0, 0.0, 0.0, 18, 'No'],
       [99.0, 1.0, 1.0, 0.0, 0.0, 0.0, 66, 'No'],
       [104.0, 0.0, 1.0, 0.0, 0.0, 1.0, 44, 'No'],
       [101.0, 0.0, 1.0, 1.0, 0.0, 0.0, 19, 'Yes'],
       [100.0, 1.0, 0.0, 0.0, 1.0, 0.0, 11, 'Yes'],
       [100.0, 1.0, 0.0, 0.0, 0.0, 0.0, 47, 'Yes'],
       [98.0, 0.0, 1.0, 1.0, 0.0, 0.0, 83, 'Yes'],
       [99.0, 0.0, 0.0, 0.0, 0.0, 1.0, 60, 'Yes'],
       [101.0, 0.0, 0.0, 0.0, 0.0, 1.0, 81, 'Yes'],
       [101.0, 1.0, 1.0, 0.0, 1.0, 0.0, 71, 'No'],
       [99.0, 1.0, 0.0, 0.0, 0.0, 0.0, 49, 'No'],
       [98.0, 1.0, 1.0, 0.0, 0.0, 1.0, 23, 'Yes'],
       [104.0, 0.0, 0.0, 0.0, 1.0, 0.0, 6, 'Yes'],
       [102.0, 1.0, 0.0, 0.0, 0.0, 0.0, 24, 'Yes'],
       [98.0, 1.0, 0.0, 0.0, 0.0, 1.0, 81, 'No'],
       [104.0, 1.0, 0.0, 0.0, 0.0, 0.0, 56, 'Yes'],
       [100.0, 0.0, 1.0, 0.0, 0.0, 0.0, 10, 'No'],
       [104.0, 0.0, 1.0, 0.0, 0.0, 1.0, 42, 'No'],
       [102.0, 0.0, 0.0, 0.0, 0.0, 0.0, 69, 'No'],
       [104.0, 0.0, 1.0, 0.0, 1.0, 0.0, 51, 'No'],
       [99.0, 0.0, 1.0, 0.0, 0.0, 0.0, 65, 'No'],
       [104.0, 1.0, 0.0, 0.0, 1.0, 0.0, 54, 'No'],
       [103.0, 0.0, 0.0, 1.0, 0.0, 0.0, 73, 'No'],
       [101.0, 1.0, 0.0, 1.0, 0.0, 0.0, 68, 'No'],
       [104.0, 1.0, 0.0, 1.0, 0.0, 0.0, 75, 'No'],
       [101.0, 0.0, 0.0, 0.0, 1.0, 0.0, 83, 'No'],
       [98.0, 1.0, 1.0, 0.0, 1.0, 0.0, 34, 'Yes'],
       [104.0, 1.0, 0.0, 1.0, 0.0, 0.0, 34, 'No'],
       [102.0, 0.0, 1.0, 0.0, 1.0, 0.0, 5, 'Yes'],
       [100.0, 0.0, 1.0, 0.0, 0.0, 0.0, 80, 'Yes'],
       [101.0, 0.0, 0.0, 0.0, 1.0, 0.0, 8, 'No'],
       [100.0, 0.0, 1.0, 0.0, 0.0, 0.0, 11, 'Yes'],
       [103.0, 0.0, 0.0, 0.0, 1.0, 0.0, 48, 'Yes'],
       [99.0, 0.0, 0.0, 0.0, 0.0, 1.0, 14, 'Yes'],
       [99.0, 0.0, 1.0, 1.0, 0.0, 0.0, 65, 'No'],
       [98.0, 0.0, 1.0, 0.0, 1.0, 0.0, 24, 'Yes'],
       [104.0, 0.0, 0.0, 0.0, 1.0, 0.0, 17, 'No'],
       [98.0, 1.0, 0.0, 0.0, 0.0, 1.0, 69, 'No'],
       [103.0, 0.0, 0.0, 0.0, 0.0, 0.0, 16, 'Yes'],
       [104.0, 0.0, 1.0, 0.0, 0.0, 0.0, 25, 'Yes'],
       [101.0, 1.0, 1.0, 0.0, 0.0, 0.0, 47, 'No'],
       [100.0, 0.0, 0.0, 0.0, 1.0, 0.0, 5, 'No'],
       [103.0, 1.0, 1.0, 0.0, 0.0, 0.0, 46, 'No'],
       [99.0, 1.0, 0.0, 1.0, 0.0, 0.0, 59, 'No'],
       [101.0, 0.0, 1.0, 1.0, 0.0, 0.0, 38, 'Yes'],
       [102.0, 1.0, 0.0, 0.0, 1.0, 0.0, 82, 'No'],
       [100.0, 0.0, 1.0, 0.0, 1.0, 0.0, 27, 'Yes'],
       [101.0, 1.0, 1.0, 0.0, 1.0, 0.0, 79, 'Yes'],
       [104.0, 0.0, 0.0, 0.0, 0.0, 0.0, 12, 'No'],
       [101.0, 1.0, 0.0, 0.0, 1.0, 0.0, 51, 'Yes'],
       [101.0, 0.0, 0.0, 0.0, 0.0, 0.0, 20, 'No'],
       [98.0, 1.0, 0.0, 0.0, 0.0, 1.0, 5, 'No'],
       [98.0, 1.0, 0.0, 0.0, 1.0, 0.0, 10, 'Yes']], dtype=object)