In [1]:
import pandas as pd

In [2]:
from sklearn.model_selection import train_test_split

In [6]:
df = pd.read_csv('500hits.csv', encoding='latin-1')

In [4]:
import chardet

with open('500hits.csv', 'rb') as f:
    result = chardet.detect(f.read(10000))  # check first 10 KB
print(result)

{'encoding': 'ascii', 'confidence': 1.0, 'language': ''}

In [7]:
df.head()

,PLAYER,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,BA,HOF
0,Ty Cobb,24,3035,11434,2246,4189,724,295,117,726,1249,357,892,178,0.366,1
1,Stan Musial,22,3026,10972,1949,3630,725,177,475,1951,1599,696,78,31,0.331,1
2,Tris Speaker,22,2789,10195,1882,3514,792,222,117,724,1381,220,432,129,0.345,1
3,Derek Jeter,20,2747,11195,1923,3465,544,66,260,1311,1082,1840,358,97,0.310,1
4,Honus Wagner,21,2792,10430,1736,3430,640,252,101,0,963,327,722,15,0.329,1

In [8]:
X = df.drop(columns=['PLAYER', 'HOF'])

In [9]:
X.head(2)

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,BA
0,24,3035,11434,2246,4189,724,295,117,726,1249,357,892,178,0.366
1,22,3026,10972,1949,3630,725,177,475,1951,1599,696,78,31,0.331

In [10]:
X.describe()

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,BA
count,465.000000,465.000000,465.000000,465.000000,465.000000,465.000000,465.000000,465.000000,465.000000,465.00000,465.000000,465.000000,465.000000,465.000000
mean,17.049462,2048.698925,7511.455914,1150.313978,2170.247312,380.952688,78.554839,201.049462,894.260215,783.56129,847.470968,195.905376,58.083871,0.288712
std,2.765186,354.391805,1294.065992,289.635071,424.190773,96.483460,49.363030,143.622664,486.193456,327.43195,489.224289,181.845543,48.027509,0.021208
min,11.000000,1331.000000,4981.000000,601.000000,1660.000000,177.000000,3.000000,9.000000,0.000000,239.00000,0.000000,7.000000,0.000000,0.246000
25%,15.000000,1802.000000,6523.000000,936.000000,1838.000000,312.000000,41.000000,79.000000,640.000000,535.00000,436.000000,63.000000,22.000000,0.273000
50%,17.000000,1993.000000,7241.000000,1104.000000,2076.000000,366.000000,67.000000,178.000000,968.000000,736.00000,825.000000,137.000000,52.000000,0.287000
75%,19.000000,2247.000000,8180.000000,1296.000000,2375.000000,436.000000,107.000000,292.000000,1206.000000,955.00000,1226.000000,285.000000,84.000000,0.300000
max,26.000000,3308.000000,12364.000000,2295.000000,4189.000000,792.000000,309.000000,755.000000,2297.000000,2190.00000,2597.000000,1406.000000,335.000000,0.366000

In [11]:
X.shape

(465, 14)

In [12]:
X.isnull().sum()

YRS    0
G      0
AB     0
R      0
H      0
2B     0
3B     0
HR     0
RBI    0
BB     0
SO     0
SB     0
CS     0
BA     0
dtype: int64

In [13]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 465 entries, 0 to 464
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   YRS     465 non-null    int64
 1   G       465 non-null    int64
 2   AB      465 non-null    int64
 3   R       465 non-null    int64
 4   H       465 non-null    int64
 5   2B      465 non-null    int64
 6   3B      465 non-null    int64
 7   HR      465 non-null    int64
 8   RBI     465 non-null    int64
 9   BB      465 non-null    int64
 10  SO      465 non-null    int64
 11  SB      465 non-null    int64
 12  CS      465 non-null    int64
 13  BA      465 non-null    float64
dtypes: float64(1), int64(13)
memory usage: 51.0 KB