In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
# to fill a row or column with random data linear models are best
# may not work for decision trees though
#But covariance is gets affected
# Not memory efficient->keeping training data at server

In [5]:
from sklearn.model_selection import train_test_split as tts

In [9]:
df = pd.read_csv('train again.csv')

In [10]:
df.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [14]:
df=df[['Age', 'Fare', 'Survived']]

In [15]:
df.head(3)

    Age     Fare  Survived
0  22.0   7.2500         0
1  38.0  71.2833         1
2  26.0   7.9250         1

In [16]:
df.isnull().sum()

Age         177
Fare          0
Survived      0
dtype: int64

In [17]:
df.isnull().mean()

Age         0.198653
Fare        0.000000
Survived    0.000000
dtype: float64

In [18]:
X=df.iloc[:, 0:2]
y=df.iloc[:,-1]

In [19]:
X

      Age     Fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
886  27.0  13.0000
887  19.0  30.0000
888   NaN  23.4500
889  26.0  30.0000
890  32.0   7.7500

[891 rows x 2 columns]

In [20]:
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [21]:
X_train,X_test,y_train,y_test=tts(X,y,test_size=0.2,random_state=2)

In [22]:
X_train['Age_imputed'] = X_train['Age']
X_test['Age_imputed'] = X_test['Age']

In [23]:
X_train

      Age      Fare  Age_imputed
30   40.0   27.7208         40.0
10    4.0   16.7000          4.0
873  47.0    9.0000         47.0
182   9.0   31.3875          9.0
876  20.0    9.8458         20.0
..    ...       ...          ...
534  30.0    8.6625         30.0
584   NaN    8.7125          NaN
493  71.0   49.5042         71.0
527   NaN  221.7792          NaN
168   NaN   25.9250          NaN

[712 rows x 3 columns]