In [1]:
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [3]:
data = pd.read_csv('play_tennis.csv')

In [4]:
data.head(2)

  day outlook temp humidity    wind play
0  D1   Sunny  Hot     High    Weak   No
1  D2   Sunny  Hot     High  Strong   No

In [6]:
data.drop(columns =['day'], inplace=True)

In [7]:
data.head(3)

    outlook temp humidity    wind play
0     Sunny  Hot     High    Weak   No
1     Sunny  Hot     High  Strong   No
2  Overcast  Hot     High    Weak  Yes

In [8]:
# 1
# Sunny, Hot, High, Weak , play yes or no?

In [13]:
#P(Yes/Sunny,Hot,High,Weak)=
#                P(Sunny/Yes)*P(Hot/Yes)*P(High/Yes)*P(Weak/Yes)*P(Yes)

In [16]:
#P(No/Sunny,Hot,High,Weak)=
#                 P(Sunny/No)*P(Hot/No)*P(High/No)*P(Weak/No)*P(No)

In [17]:
#P(yes) and P(No)

In [18]:
data['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [20]:
py = 9/14
pn = 5/14

In [21]:
py

0.6428571428571429

In [23]:
# Outlook Columns
pd.crosstab(data['outlook'], data['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [32]:
Pon = 0
Prn = 2/5
psn = 3/5

Poy = 4/9
Pry = 3/9
psy = 2/9

In [33]:
pd.crosstab(data['temp'], data['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [34]:
PCoolNo = 1/5
PHotNo = 2/5
PMildNo = 2/5

PCoolYes = 3/9
PHotYes = 2/9
PMildYes = 4/9

In [35]:
pd.crosstab(data['humidity'], data['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [36]:
PHighNo = 4/5
PNormalNo = 1/5

PHighYes = 1/3
PNormalYes = 2/3

In [37]:
pd.crosstab(data['wind'], data['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [38]:
PStrongNo = 3/5
PWeakNo = 2/5

PStrongYes = 3/9
PWeakYes = 6/9

In [40]:
# Sunny, Hot, High, Weak
Pyes = psy*PHotYes*PHighYes*PWeakYes*py

In [41]:
Pyes

0.007054673721340387

In [42]:
Pn = psn*PHotNo*PHighNo*PWeakNo*pn

In [43]:
Pn

0.02742857142857143

In [44]:
# Conclude = No Play