## Sentiment Analysis Project

 # Video 10

In [1]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("IMDB Dataset.csv")

In [3]:
df.head(3)

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive

In [4]:
df.shape

(50000, 2)

In [5]:
df['sentiment'].value_counts()

sentiment
positive    25000
negative    25000
Name: count, dtype: int64

In [6]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [7]:
df['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

In [8]:
df = df.sample(10000)

In [9]:
df.shape

(10000, 2)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 49107 to 14475
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     10000 non-null  object
 1   sentiment  10000 non-null  object
dtypes: object(2)
memory usage: 234.4+ KB

In [11]:
df['sentiment'].replace({'positive': 1, 'negative':0}, inplace=True)

C:\Users\dell\AppData\Local\Temp\ipykernel_6484\3116613263.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['sentiment'].replace({'positive': 1, 'negative':0}, inplace=True)
C:\Users\dell\AppData\Local\Temp\ipykernel_6484\3116613263.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['sentiment'].replace({'positive': 1, 'negative':0}, inplace=True)

In [12]:
df.head(2)

                                                  review  sentiment
49107  <br /><br />It's a generic coming-of-age story...          1
19140  The late, great Robert Bloch (author of PSYCHO...          1

In [13]:
import re
clean = re.compile('<.*?>')
re.sub(clean, '', df.iloc[2].review)

"There are so many words I want to use to describe this movie, but can't really do that can I? This movie is a movie to watch if you just want to sit, laugh, cry and then pee. I'm serious. Don't watch this movie if you're easily offended by profanity, sex, nudity, homosexuality...and everything else associated with nature. Being a woman, and that might not even be a factor, I can watch this movie over and over again. Trey Parker and Matt Stone are absolutely brilliant. Along with all their other debuts, I think Baseketball is the prize winner. I'm laughing now just thinking about some of the stupid things they do in the movie. Watch the movie!! That's all I'm going to say. It's sort of hard for me to leave this comment because I'm one of those people, like Ozzy Osbourne, who has a curse word in almost every line that blurts out of their mouth when they speak. So I'm keeping it professional. Best movie. Heck yeah!!"

In [14]:
df.head(3)

                                                  review  sentiment
49107  <br /><br />It's a generic coming-of-age story...          1
19140  The late, great Robert Bloch (author of PSYCHO...          1
44316  There are so many words I want to use to descr...          1

In [15]:
df.iloc[2].review

"There are so many words I want to use to describe this movie, but can't really do that can I? This movie is a movie to watch if you just want to sit, laugh, cry and then pee. I'm serious. Don't watch this movie if you're easily offended by profanity, sex, nudity, homosexuality...and everything else associated with nature. Being a woman, and that might not even be a factor, I can watch this movie over and over again. Trey Parker and Matt Stone are absolutely brilliant. Along with all their other debuts, I think Baseketball is the prize winner. I'm laughing now just thinking about some of the stupid things they do in the movie. Watch the movie!! That's all I'm going to say. It's sort of hard for me to leave this comment because I'm one of those people, like Ozzy Osbourne, who has a curse word in almost every line that blurts out of their mouth when they speak. So I'm keeping it professional. Best movie. Heck yeah!!"

In [16]:
def clean_html(text):
    clean = re.compile('<.*?>')
    return re.sub(clean, '', text)

In [17]:
df['review'] = df['review'].apply(clean_html)

In [18]:
df['review'].sample(1)

31058    When I first watched this film, I thought that...
Name: review, dtype: object

In [19]:
def convert_lower(text):
    return text.lower()

In [20]:
df['review'] = df['review'].apply(convert_lower)

In [21]:
df['review'].sample(1).values

array(['good to see i\'m not the only person who remembers this great film. i have very fond memories of this movie - seem to vaguely remember back to when i was about 8 and i\'d watch the kids tv shows after school (broom cupboard anyone?). this was the first and last film to scare me - and the images of the boy surrounded by mist on a hill will stay with me forever! like most films of this era, it has a happy ending - aimed at children, but with a definite ability to capture an adults attention. the lovely cornish scenery really sets the film up to feel isolated - and the "ghostly" scenes are simple but very, very effective! i\'d love to try and find this movie again - see if it still hits home!'],
      dtype=object)

In [22]:
def remove_special(text):
    x=''
    for i in text:
        if i.isalnum():
            x+=i
        else: 
            x=x+' '
      
    return x

In [23]:
df['review'] = df['review'].apply(remove_special)

In [24]:
import nltk

In [25]:
from nltk.corpus import stopwords

In [26]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\dell\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [27]:
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each',
 'few',
 'more',
 'most',
 'other',
 'some',
 'such',
 'no',
 'nor',
 'not',
 'only',
 'own',
 'same',
 'so',
 'than',
 'too',
 'very',
 's',
 't',
 'can',
 'will',
 'just',
 'don',
 "don't",
 'should',
 "should've",
 'now',
 'd',
 'll',
 'm',
 'o',
 're',
 've',
 'y',
 'ain',
 'aren',
 "aren't",
 'couldn',
 "couldn't",
 'didn',
 "didn't",
 'doesn',
 "doesn't",
 'hadn',
 "hadn't",
 'hasn',
 "hasn't",
 'haven',
 "haven't",
 'isn',
 "isn't",
 'ma',
 'mightn',
 "mightn't",
 'mustn',
 "mustn't",
 'needn',
 "needn't",
 'shan',
 "shan't",
 'shouldn',
 "shouldn't",
 'wasn',
 "wasn't",
 'weren',
 "weren't",
 'won',
 "won't",
 'wouldn',
 "wouldn't"]

In [28]:
len(stopwords.words('english'))

179

In [29]:
def remove_stopwords(text):
    x=[]
    for i in text.split():
        if i not in stopwords.words('english'):
            x.append(i)
        
    y = x[:]
    x.clear()
    return y

In [30]:
df['review']=df['review'].apply(remove_stopwords)

In [31]:
df

                                                  review  sentiment
49107  [generic, coming, age, story, think, member, w...          1
19140  [late, great, robert, bloch, author, psycho, p...          1
44316  [many, words, want, use, describe, movie, real...          1
29378  [indie, film, looks, lives, group, people, tak...          1
40004  [movie, v, day, enjoy, first, george, jungle, ...          0
...                                                  ...        ...
10892  [semana, santa, jaw, droppingly, bad, wrong, m...          0
29388  [hammer, completist, dreading, time, would, ra...          0
39676  [sometimes, seeking, movie, nothing, except, g...          1
49733  [read, book, based, adaptation, bother, hated,...          0
14475  [saw, movie, coming, could, wait, see, say, di...          0

[10000 rows x 2 columns]

In [32]:
from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()

y = []
def stem_words(text):
    for i in text:
        y.append(ps.stem(i))
    z = y[:]
    y.clear()
    return z

In [33]:
df['review'] = df['review'].apply(stem_words)

In [34]:
df.head(3)

                                                  review  sentiment
49107  [gener, come, age, stori, think, member, wed, ...          1
19140  [late, great, robert, bloch, author, psycho, p...          1
44316  [mani, word, want, use, describ, movi, realli,...          1

In [35]:
def join_back(list_input):
    return " ".join(list_input)

In [36]:
df['review'] = df['review'].apply(join_back)

In [37]:
df.head(2)

                                                  review  sentiment
49107  gener come age stori think member wed summer 4...          1
19140  late great robert bloch author psycho pay atte...          1

In [62]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=1000)

In [63]:
X = cv.fit_transform(df['review']).toarray()

In [64]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [65]:
X.shape

(10000, 1000)

In [66]:
X[0].max()

3

In [67]:
X[0].mean()

0.077

In [68]:
y = df.iloc[:, -1].values

In [69]:
y.shape

(10000,)

In [70]:
from sklearn.model_selection import train_test_split

In [71]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)

In [72]:
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB

In [73]:
clf1 = GaussianNB()
clf2 = MultinomialNB()
clf3 = BernoulliNB()

In [74]:
clf1.fit(X_train, y_train)
clf2.fit(X_train, y_train)
clf3.fit(X_train, y_train)

BernoulliNB()

In [75]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)
y_pred3 = clf3.predict(X_test)

In [76]:
from sklearn.metrics import accuracy_score

In [77]:
print("Accuracy of GaussNB is :", accuracy_score(y_test,y_pred1)*100)
print("Accuracy of MultiNB is:", accuracy_score(y_test,y_pred2)*100)
print("Accuracy of BernauNB is :", accuracy_score(y_test,y_pred3)*100)

Accuracy of GaussNB is : 77.35
Accuracy of MultiNB is: 82.89999999999999
Accuracy of BernauNB is : 83.0