In [2]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
# Two techniques to convert numerical data to categorical data
# Discretization(also called Binning)->interval banauney->histrogram jastai
# Another is Binarization

In [5]:
# Types of Binning
# Unsupervised
    #Equal width(uniform)
    #Equal frequency(quantile)
    #Kmeans Binning
# Supervised
    #Decision Tree Bining(not covered here though)
# Custom Binning

In [9]:
# Equal Width Binning
# interval = (max-min)/(no of bins entered by the user)

In [10]:
# Easier to handle outliers
# Spread of the data doesn't change

In [12]:
# For uniform frequency binning, 
# for 10 intervals
# Each interval will contain 10% of the total observation
# Benefits
    # Used more than equal width binning
    # value spread becomes uniform
    # robust to outliers

In [13]:
# K means Binning
    # Generally used when the data is in clusters
    # Otherwise remaining two are used

In [14]:
from sklearn.model_selection import train_test_split as tts
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import KBinsDiscretizer
from sklearn.compose import ColumnTransformer

In [16]:
df = pd.read_csv('train.csv', usecols=['Age','Fare','Survived'])

In [17]:
df.dropna(inplace=True)

In [18]:
df.shape

(714, 3)

In [19]:
df.head(2)

   Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833

In [20]:
X=df.drop(columns=['Survived'])
y=df['Survived']

In [21]:
X

      Age     Fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
885  39.0  29.1250
886  27.0  13.0000
887  19.0  30.0000
889  26.0  30.0000
890  32.0   7.7500

[714 rows x 2 columns]

In [22]:

y

0      0
1      1
2      1
3      1
4      0
      ..
885    0
886    0
887    1
889    1
890    0
Name: Survived, Length: 714, dtype: int64

In [23]:
X_train,X_test,y_train,y_test=tts(X,y,test_size=0.2, random_state=42)

In [24]:
X_train.head(2)

      Age     Fare
328  31.0  20.5250
73   26.0  14.4542

In [25]:
clf = DecisionTreeClassifier()

In [26]:
clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)

In [27]:
accuracy_score(y_test,y_pred)

0.6293706293706294

In [28]:
np.mean(cross_val_score(clf,X_train,y_train,scoring='accuracy'))

0.640976353928299

In [37]:
kbin_age=KBinsDiscretizer(n_bins=15, encode='ordinal', strategy='uniform')
kbin_fare=KBinsDiscretizer(n_bins=15,encode='ordinal',strategy='kmeans')

In [38]:
trf=ColumnTransformer([
    ('first', kbin_age,[0]),
    ('second', kbin_fare,[1])
])

In [39]:
X_train_trf=trf.fit_transform(X_train)
X_test_trf=trf.transform(X_test)

In [40]:
trf.named_transformers_['first'].n_bins_

array([15])

In [41]:
trf.named_transformers_

{'first': KBinsDiscretizer(encode='ordinal', n_bins=15, strategy='uniform'),
 'second': KBinsDiscretizer(encode='ordinal', n_bins=15, strategy='kmeans')}

In [42]:
clf2 = DecisionTreeClassifier()
clf2.fit(X_train_trf,y_train)

DecisionTreeClassifier()

In [43]:
y_pred2=clf2.predict(X_test)

C:\Users\dell\anaconda3\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but DecisionTreeClassifier was fitted without feature names
  warnings.warn(

In [44]:
accuracy_score(y_pred2, y_test)

0.5944055944055944