In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('covid_toy.csv')

In [3]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [4]:
df.head(4)

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No

In [5]:
df.shape

(100, 6)

In [6]:
from sklearn.model_selection import train_test_split as tts

In [7]:
X_train, X_test, y_train, y_test = tts(df.drop(columns = ['has_covid']),
                                      df['has_covid'], test_size=0.2)

In [8]:
X_train.head(3)

    age  gender  fever   cough     city
83   17  Female  104.0    Mild  Kolkata
27   33  Female  102.0  Strong    Delhi
92   82  Female  102.0  Strong  Kolkata

In [9]:
X_train.shape

(80, 5)

In [10]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [11]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [12]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [13]:
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])
X_test_fever = si.fit_transform(X_test[['fever']])

In [14]:
X_train_fever.shape

(80, 1)

In [15]:
df.sample()

    age  gender  fever cough    city has_covid
11   65  Female   98.0  Mild  Mumbai       Yes

In [16]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [20]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories = [['Mild', 'Strong']])

In [23]:
X_train_cough = oe.fit_transform(X_train[['cough']])

In [42]:
X_test_cough = oe.fit_transform(X_test[['cough']])

In [26]:
X_train_cough.shape

(80, 1)

In [29]:
from sklearn.preprocessing import OneHotEncoder as OHE

In [30]:
ohe = OHE(drop='first', sparse=False)

In [31]:
X_train_gender_city = ohe.fit_transform(X_train[['gender', 'city']])

C:\Users\dell\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [32]:
X_test_gender_city = ohe.fit_transform(X_test[['gender', 'city']])

C:\Users\dell\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [33]:
X_train_gender_city.shape

(80, 4)

In [34]:
X_test_gender_city.shape

(20, 4)

In [37]:
X_train_age = X_train.drop(columns = ['gender', 'fever', 'cough', 'city']).values

In [38]:
X_test_age = X_test.drop(columns = ['gender', 'fever', 'cough', 'city']).values

In [39]:
X_train_age.shape

(80, 1)

In [43]:
X_train_transformed = np.concatenate((X_train_age, X_train_fever, 
                                     X_train_gender_city, X_train_cough),
                                    axis =1)
X_test_transformed = np.concatenate((X_test_age, X_test_fever, 
                                     X_test_gender_city, X_test_cough),
                                    axis =1)

## Mentos Zindagi

In [45]:
from sklearn.compose import ColumnTransformer

In [48]:
transformer = ColumnTransformer(transformers = [
    ('tnf1', SimpleImputer(), ['fever']),
    ('tnf2', OrdinalEncoder(categories =[['Mild', 'Strong']]), ['cough']),
    ('tnf3', OneHotEncoder(sparse=False, drop='first'), ['gender','city']) 
], remainder = 'passthrough')

In [50]:
transformer.fit_transform(X_train).shape

C:\Users\dell\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

(80, 7)

In [51]:
transformer.fit_transform(X_test).shape

C:\Users\dell\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

(20, 7)

In [52]:
X_train

    age  gender  fever   cough       city
83   17  Female  104.0    Mild    Kolkata
27   33  Female  102.0  Strong      Delhi
92   82  Female  102.0  Strong    Kolkata
91   38    Male    NaN    Mild      Delhi
15   70    Male  103.0  Strong    Kolkata
..  ...     ...    ...     ...        ...
49   44    Male  104.0    Mild     Mumbai
71   75  Female  104.0  Strong      Delhi
58   23    Male   98.0  Strong     Mumbai
23   80  Female   98.0    Mild      Delhi
18   64  Female   98.0    Mild  Bangalore

[80 rows x 5 columns]

In [54]:
transformer.fit_transform(X_test)

C:\Users\dell\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

array([[ 98.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  31.        ],
       [101.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  47.        ],
       [100.94444444,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  42.        ],
       [103.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  48.        ],
       [100.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  55.        ],
       [100.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  13.        ],
       [100.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   5.        ],
       [104.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  51.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  81.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  83.        ],
       [ 98.        ,   1.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  34.        ],
       [100.94444444,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  34.        ],
       [102.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   5.        ],
       [ 99.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  65.        ],
       [102.        ,   1.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  20.        ],
       [ 99.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  14.        ],
       [104.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  34.        ],
       [103.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  46.        ],
       [103.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  50.        ],
       [ 99.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  25.        ]])