In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('customer.csv')

In [3]:
df.head(2)

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No

In [10]:
from sklearn.model_selection import train_test_split as tts
X_train,X_test,y_train,y_test = tts(df.iloc[:,2:4], df.iloc[:,-1],
                                   test_size=0.2)

In [11]:
from sklearn.preprocessing import OrdinalEncoder

In [12]:
X_train

     review education
19     Poor        PG
24  Average        PG
45     Poor        PG
29  Average        UG
16     Poor        UG
6      Good    School
9      Good        UG
46     Poor        PG
25     Good    School
10     Good        UG
49     Good        UG
21  Average        PG
8   Average        UG
43     Poor        PG
26     Poor        PG
36     Good        UG
42     Good        PG
37  Average        PG
18     Good    School
40     Good    School
4   Average        UG
48     Good        UG
13  Average    School
30  Average        UG
23     Good    School
38     Good    School
35     Poor    School
32  Average        UG
7      Poor    School
3      Good        PG
31     Poor    School
17     Poor        UG
1      Poor        UG
27     Poor        PG
12     Poor    School
33     Good        PG
5   Average    School
44  Average        UG
28     Poor    School
39     Poor        PG

In [18]:
oe = OrdinalEncoder(categories=[['Poor', 'Average', 'Good'],
                               ['School', 'UG', 'PG']])

In [20]:
!pip install --upgrade scikit-learn

Requirement already satisfied: scikit-learn in c:\users\dell\anaconda3\lib\site-packages (1.3.0)
Collecting scikit-learn
  Obtaining dependency information for scikit-learn from https://files.pythonhosted.org/packages/17/1c/ccdd103cfcc9435a18819856fbbe0c20b8fa60bfc3343580de4be13f0668/scikit_learn-1.5.2-cp311-cp311-win_amd64.whl.metadata
  Downloading scikit_learn-1.5.2-cp311-cp311-win_amd64.whl.metadata (13 kB)
Requirement already satisfied: numpy>=1.19.5 in c:\users\dell\anaconda3\lib\site-packages (from scikit-learn) (1.24.3)
Requirement already satisfied: scipy>=1.6.0 in c:\users\dell\anaconda3\lib\site-packages (from scikit-learn) (1.10.1)
Collecting joblib>=1.2.0 (from scikit-learn)
  Obtaining dependency information for joblib>=1.2.0 from https://files.pythonhosted.org/packages/91/29/df4b9b42f2be0b623cbd5e2140cafcaa2bef0759a00b7b70104dcfe2fb51/joblib-1.4.2-py3-none-any.whl.metadata
  Downloading joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn)
  Obtaining dependency information for threadpoolctl>=3.1.0 from https://files.pythonhosted.org/packages/4b/2c/ffbf7a134b9ab11a67b0cf0726453cedd9c5043a4fe7a35d1cefa9a1bcfb/threadpoolctl-3.5.0-py3-none-any.whl.metadata
  Downloading threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.5.2-cp311-cp311-win_amd64.whl (11.0 MB)
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB 1.3 MB/s eta 0:00:09
   ---------------------------------------- 0.1/11.0 MB 656.4 kB/s eta 0:00:17
   ---------------------------------------- 0.1/11.0 MB 871.5 kB/s eta 0:00:13
    --------------------------------------- 0.2/11.0 MB 1.0 MB/s eta 0:00:11
    --------------------------------------- 0.3/11.0 MB 1.2 MB/s eta 0:00:10
   - -------------------------------------- 0.5/11.0 MB 1.9 MB/s eta 0:00:06
   -- ------------------------------------- 0.7/11.0 MB 2.1 MB/s eta 0:00:05
   --- ------------------------------------ 1.0/11.0 MB 2.7 MB/s eta 0:00:04
   ---- ----------------------------------- 1.2/11.0 MB 2.9 MB/s eta 0:00:04
   ----- ---------------------------------- 1.5/11.0 MB 3.3 MB/s eta 0:00:03
   ------ --------------------------------- 1.7/11.0 MB 3.4 MB/s eta 0:00:03
   ------- -------------------------------- 2.0/11.0 MB 3.7 MB/s eta 0:00:03
   -------- ------------------------------- 2.2/11.0 MB 3.9 MB/s eta 0:00:03
   --------- ------------------------------ 2.5/11.0 MB 3.9 MB/s eta 0:00:03
   ---------- ----------------------------- 2.8/11.0 MB 4.1 MB/s eta 0:00:03
   ----------- ---------------------------- 3.1/11.0 MB 4.2 MB/s eta 0:00:02
   ------------ --------------------------- 3.4/11.0 MB 4.3 MB/s eta 0:00:02
   ------------- -------------------------- 3.6/11.0 MB 4.4 MB/s eta 0:00:02
   -------------- ------------------------- 4.0/11.0 MB 4.5 MB/s eta 0:00:02
   -------------- ------------------------- 4.1/11.0 MB 4.5 MB/s eta 0:00:02
   ---------------- ----------------------- 4.4/11.0 MB 4.6 MB/s eta 0:00:02
   ---------------- ----------------------- 4.6/11.0 MB 4.6 MB/s eta 0:00:02
   ----------------- ---------------------- 4.9/11.0 MB 4.6 MB/s eta 0:00:02
   ------------------ --------------------- 5.2/11.0 MB 4.6 MB/s eta 0:00:02
   ------------------- -------------------- 5.4/11.0 MB 4.7 MB/s eta 0:00:02
   -------------------- ------------------- 5.7/11.0 MB 4.8 MB/s eta 0:00:02
   --------------------- ------------------ 5.9/11.0 MB 4.7 MB/s eta 0:00:02
   ---------------------- ----------------- 6.2/11.0 MB 4.8 MB/s eta 0:00:02
   ----------------------- ---------------- 6.5/11.0 MB 4.8 MB/s eta 0:00:01
   ------------------------ --------------- 6.7/11.0 MB 4.8 MB/s eta 0:00:01
   ------------------------- -------------- 6.9/11.0 MB 4.8 MB/s eta 0:00:01
   -------------------------- ------------- 7.2/11.0 MB 4.9 MB/s eta 0:00:01
   --------------------------- ------------ 7.5/11.0 MB 4.9 MB/s eta 0:00:01
   ---------------------------- ----------- 7.8/11.0 MB 5.0 MB/s eta 0:00:01
   ---------------------------- ----------- 8.0/11.0 MB 4.9 MB/s eta 0:00:01
   ------------------------------ --------- 8.3/11.0 MB 4.9 MB/s eta 0:00:01
   ------------------------------ --------- 8.5/11.0 MB 5.0 MB/s eta 0:00:01
   ------------------------------- -------- 8.7/11.0 MB 5.0 MB/s eta 0:00:01
   -------------------------------- ------- 9.0/11.0 MB 5.0 MB/s eta 0:00:01
   --------------------------------- ------ 9.3/11.0 MB 5.0 MB/s eta 0:00:01
   ---------------------------------- ----- 9.6/11.0 MB 5.0 MB/s eta 0:00:01
   ----------------------------------- ---- 9.7/11.0 MB 5.0 MB/s eta 0:00:01
   ------------------------------------ --- 9.9/11.0 MB 5.0 MB/s eta 0:00:01
   ------------------------------------ --- 10.2/11.0 MB 5.0 MB/s eta 0:00:01
   -------------------------------------- - 10.5/11.0 MB 5.5 MB/s eta 0:00:01
   -------------------------------------- - 10.7/11.0 MB 5.5 MB/s eta 0:00:01
   ---------------------------------------  11.0/11.0 MB 5.5 MB/s eta 0:00:01
   ---------------------------------------- 11.0/11.0 MB 5.4 MB/s eta 0:00:00
Downloading joblib-1.4.2-py3-none-any.whl (301 kB)
   ---------------------------------------- 0.0/301.8 kB ? eta -:--:--
   ----------------------- ---------------- 174.1/301.8 kB 5.3 MB/s eta 0:00:01
   ---------------------------------------- 301.8/301.8 kB 4.7 MB/s eta 0:00:00
Downloading threadpoolctl-3.5.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, joblib, scikit-learn
  Attempting uninstall: threadpoolctl
    Found existing installation: threadpoolctl 2.2.0
    Uninstalling threadpoolctl-2.2.0:
      Successfully uninstalled threadpoolctl-2.2.0
  Attempting uninstall: joblib
    Found existing installation: joblib 1.1.1
    Uninstalling joblib-1.1.1:
      Successfully uninstalled joblib-1.1.1
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.3.0
    Uninstalling scikit-learn-1.3.0:
      Successfully uninstalled scikit-learn-1.3.0
Successfully installed joblib-1.4.2 scikit-learn-1.5.2 threadpoolctl-3.5.0

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
transformers 2.1.1 requires sentencepiece, which is not installed.
pandas-profiling 3.2.0 requires joblib~=1.1.0, but you have joblib 1.4.2 which is incompatible.
ydata-profiling 4.10.0 requires visions[type_image_path]<0.7.7,>=0.7.5, but you have visions 0.7.4 which is incompatible.

In [19]:
X_train = oe.transform(X_train)

AttributeError: 'OrdinalEncoder' object has no attribute '_missing_indices'