In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv('Fortune_500.csv')

In [3]:
data.head(2)

,Rank,Title,Website,Employees,Sector,Industry,Hqlocation,Hqaddr,Hqcity,Hqstate,...,Ceo-title,Address,Ticker,Fullname,Revenues,Revchange,Profits,Prftchange,Assets,Totshequity
0,1,Walmart,http://www.walmart.com,2300000,Retailing,General Merchandisers,"Bentonville, AR",702 S.W. Eighth St.,Bentonville,AR,...,"President, Chief Executive Officer & Director","702 S.W. Eighth St., Bentonville, AR 72716",WMT,"Wal-Mart Stores, Inc.",485873,0.8,13643.0,-7.2,198825,77798.0
1,2,Berkshire Hathaway,http://www.berkshirehathaway.com,367700,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",3555 Farnam St.,Omaha,NE,...,Chairman & Chief Executive Officer,"3555 Farnam St., Omaha, NE 68131",BRKA,Berkshire Hathaway Inc.,223604,6.1,24074.0,0,620854,283001.0

In [5]:
data2=data.groupby('Sector')

data2.sum()

In [6]:
data2.sum()

C:\Users\dell\AppData\Local\Temp\ipykernel_1888\2852878774.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  data2.sum()

,Rank,Employees,Hqzip,Revenues,Revchange,Profits,Assets,Totshequity
Sector,,,,,,,,
Aerospace & Defense,2416,863840,300246,338302,-38.5,25119.7,382772,77109.0
Apparel,1456,254650,171556,66254,9.7,6318.5,55324,26972.0
Business Services,6584,845050,901384,194685,111.8,23107.1,392522,100885.0
Chemicals,3986,364906,599664,188667,31.2,15918.3,282117,86590.0
Energy,14217,869511,3411210,1176417,-444.2,370.6,2779104,914781.0
Engineering & Construction,4305,329090,673500,124682,173.8,5072.2,106590,47667.0
Financials,20815,3161998,2880322,2067607,216.2,228461.2,26816588,2656485.6
Food & Drug Stores,594,1390095,373792,389686,155.9,8522.0,172415,55028.0
"Food, Beverages & Tobacco",5698,1000309,1062524,472806,129.7,56308.4,697434,216863.0
Health Care,6952,2341423,1434179,1318389,388.5,105383.9,1598998,532817.0
"Hotels, Restaurants & Leisure",2860,1838742,534922,121189,-19.5,14510.6,167954,26720.0
Household Products,3556,483344,437838,180846,105.3,19803.7,278149,86258.0
Industrials,4506,1224296,837571,418359,-95.7,32826.1,762236,187050.7
Materials,6524,385320,974069,169755,152.8,5176.9,205832,57653.0
Media,3044,378746,471709,180767,-12.6,20034.7,339639,107713.0
Motor Vehicles & Parts,2093,819225,483278,392466,101.7,17275.8,534988,93963.3
Retailing,11414,5819887,2190294,1383281,116.8,46613.9,680238,186271.0
Technology,10524,3049348,2946965,1257589,308.0,177901.4,2080354,905126.0
Telecommunications,2079,793249,423757,459978,283.8,41272.8,1149227,280147.0
Transportation,4056,1331195,863391,354733,93.1,28395.0,440674,109514.0
Wholesalers,7567,630842,1423686,799416,111.2,11347.1,271515,64459.9

In [8]:
data2.sum(numeric_only=True)

,Rank,Employees,Hqzip,Revenues,Revchange,Profits,Assets,Totshequity
Sector,,,,,,,,
Aerospace & Defense,2416,863840,300246,338302,-38.5,25119.7,382772,77109.0
Apparel,1456,254650,171556,66254,9.7,6318.5,55324,26972.0
Business Services,6584,845050,901384,194685,111.8,23107.1,392522,100885.0
Chemicals,3986,364906,599664,188667,31.2,15918.3,282117,86590.0
Energy,14217,869511,3411210,1176417,-444.2,370.6,2779104,914781.0
Engineering & Construction,4305,329090,673500,124682,173.8,5072.2,106590,47667.0
Financials,20815,3161998,2880322,2067607,216.2,228461.2,26816588,2656485.6
Food & Drug Stores,594,1390095,373792,389686,155.9,8522.0,172415,55028.0
"Food, Beverages & Tobacco",5698,1000309,1062524,472806,129.7,56308.4,697434,216863.0
Health Care,6952,2341423,1434179,1318389,388.5,105383.9,1598998,532817.0
"Hotels, Restaurants & Leisure",2860,1838742,534922,121189,-19.5,14510.6,167954,26720.0
Household Products,3556,483344,437838,180846,105.3,19803.7,278149,86258.0
Industrials,4506,1224296,837571,418359,-95.7,32826.1,762236,187050.7
Materials,6524,385320,974069,169755,152.8,5176.9,205832,57653.0
Media,3044,378746,471709,180767,-12.6,20034.7,339639,107713.0
Motor Vehicles & Parts,2093,819225,483278,392466,101.7,17275.8,534988,93963.3
Retailing,11414,5819887,2190294,1383281,116.8,46613.9,680238,186271.0
Technology,10524,3049348,2946965,1257589,308.0,177901.4,2080354,905126.0
Telecommunications,2079,793249,423757,459978,283.8,41272.8,1149227,280147.0
Transportation,4056,1331195,863391,354733,93.1,28395.0,440674,109514.0
Wholesalers,7567,630842,1423686,799416,111.2,11347.1,271515,64459.9

In [9]:
sectors=data.groupby('Sector')

In [10]:
sectors.head()

,Rank,Title,Website,Employees,Sector,Industry,Hqlocation,Hqaddr,Hqcity,Hqstate,...,Ceo-title,Address,Ticker,Fullname,Revenues,Revchange,Profits,Prftchange,Assets,Totshequity
0,1,Walmart,http://www.walmart.com,2300000,Retailing,General Merchandisers,"Bentonville, AR",702 S.W. Eighth St.,Bentonville,AR,...,"President, Chief Executive Officer & Director","702 S.W. Eighth St., Bentonville, AR 72716",WMT,"Wal-Mart Stores, Inc.",485873,0.8,13643.0,-7.2,198825,77798.0
1,2,Berkshire Hathaway,http://www.berkshirehathaway.com,367700,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",3555 Farnam St.,Omaha,NE,...,Chairman & Chief Executive Officer,"3555 Farnam St., Omaha, NE 68131",BRKA,Berkshire Hathaway Inc.,223604,6.1,24074.0,0,620854,283001.0
2,3,Apple,http://www.apple.com,116000,Technology,"Computers, Office Equipment","Cupertino, CA",1 Infinite Loop,Cupertino,CA,...,Chief Executive Officer & Director,"1 Infinite Loop, Cupertino, CA 95014",AAPL,"Apple, Inc.",215639,-7.7,45687.0,-14.4,321686,128249.0
3,4,Exxon Mobil,http://www.exxonmobil.com,72700,Energy,Petroleum Refining,"Irving, TX",5959 Las Colinas Blvd.,Irving,TX,...,Chairman & Chief Executive Officer,"5959 Las Colinas Blvd., Irving, TX 75039",XOM,Exxon Mobil Corporation,205004,-16.7,7840.0,-51.5,330314,167325.0
4,5,McKesson,http://www.mckesson.com,68000,Wholesalers,Wholesalers: Health Care,"San Francisco, CA",1 Post St.,San Francisco,CA,...,"Chairman, President & Chief Executive Officer","1 Post St., San Francisco, CA 94104",MCK,McKesson Corporation,192487,6.2,2258.0,53,56563,8924.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282,283,Autoliv,http://www.autoliv.com,65900,Motor Vehicles & Parts,Motor Vehicles and Parts,"Auburn Hills, MI",1320 Pacific Dr.,Auburn Hills,MI,...,"Chairman, President & Chief Executive Officer","1320 Pacific Dr., Auburn Hills, MI 48326",ALV,"Autoliv, Inc.",10074,9.9,567.1,24.1,8234,3677.0
299,300,Alcoa,http://www.alcoa.com,14000,Materials,Metals,"New York, NY",390 Park Ave.,New York,NY,...,Chief Executive Officer & Director,"390 Park Ave., New York, NY 10022",AA,Alcoa Corporation,9318,3.0,-400.0,-18.3,16741,5654.0
334,335,PVH,http://www.pvh.com,26650,Apparel,Apparel,"New York, NY",200 Madison Ave.,New York,NY,...,Chairman & Chief Executive Officer,"200 Madison Ave., New York, NY 10016",PVH,PVH Corp.,8203,2.3,549.0,-4.1,11068,4805.0
370,371,Ralph Lauren,http://www.ralphlauren.com,20500,Apparel,Apparel,"New York, NY",650 Madison Ave.,New York,NY,...,"President, Chief Executive Officer & Director","650 Madison Ave., New York, NY 10022",RL,Ralph Lauren Corporation,7405,-2.8,396.0,-43.6,6213,3744.0
431,432,Hanesbrands,http://www.hanes.com,67800,Apparel,Apparel,"Winston-Salem, NC",1000 E. Hanes Mill Rd.,Winston-Salem,NC,...,Chief Executive Officer & Director,"1000 E. Hanes Mill Rd., Winston-Salem, NC 27105",HBI,Hanesbrands Inc.,6063,5.8,539.4,25.8,6908,1224.0

In [11]:
sectors.size

In [12]:
sectors.size()

Sector
Aerospace & Defense              12
Apparel                           5
Business Services                20
Chemicals                        14
Energy                           57
Engineering & Construction       13
Financials                       84
Food & Drug Stores                7
Food, Beverages & Tobacco        24
Health Care                      38
Hotels, Restaurants & Leisure    10
Household Products               12
Industrials                      19
Materials                        19
Media                            11
Motor Vehicles & Parts            9
Retailing                        47
Technology                       43
Telecommunications               10
Transportation                   17
Wholesalers                      29
dtype: int64

In [13]:
sectors.get_group('Aerospace & Defense')

,Rank,Title,Website,Employees,Sector,Industry,Hqlocation,Hqaddr,Hqcity,Hqstate,...,Ceo-title,Address,Ticker,Fullname,Revenues,Revchange,Profits,Prftchange,Assets,Totshequity
23,24,Boeing,http://www.boeing.com,150540,Aerospace & Defense,Aerospace and Defense,"Chicago, IL",100 N. Riverside Plaza,Chicago,IL,...,"Chairman, President & Chief Executive Officer","100 N. Riverside Plaza, Chicago, IL 60606",BA,The Boeing Company,94571,-1.6,4895.0,-5.4,89997,817.0
49,50,United Technologies,http://www.utc.com,201600,Aerospace & Defense,Aerospace and Defense,"Farmington, CT",10 Farm Springs Rd.,Farmington,CT,...,"Chairman, President & Chief Executive Officer","10 Farm Springs Rd., Farmington, CT 06032",UTX,United Technologies Corporation,57244,-6.2,5055.0,-33.6,89706,27579.0
55,56,Lockheed Martin,http://www.lockheedmartin.com,97000,Aerospace & Defense,Aerospace and Defense,"Bethesda, MD",6801 Rockledge Dr.,Bethesda,MD,...,"Chairman, President & Chief Executive Officer","6801 Rockledge Dr., Bethesda, MD 20817",LMT,Lockheed Martin Corporation,50658,9.8,5302.0,47.1,47806,1511.0
89,90,General Dynamics,http://www.generaldynamics.com,98800,Aerospace & Defense,Aerospace and Defense,"Falls Church, VA",2941 Fairview Park Dr.,Falls Church,VA,...,Chairman & Chief Executive Officer,"2941 Fairview Park Dr., Falls Church, VA 22042",GD,General Dynamics Corporation,31353,-0.4,2955.0,-0.3,32872,10976.0
113,114,Northrop Grumman,http://www.northropgrumman.com,67000,Aerospace & Defense,Aerospace and Defense,"Falls Church, VA",2980 Fairview Park Dr.,Falls Church,VA,...,"Chairman, President & Chief Executive Officer","2980 Fairview Park Dr., Falls Church, VA 22042",NOC,Northrop Grumman Corporation,24508,4.2,2200.0,10.6,25614,5259.0
115,116,Raytheon,http://www.raytheon.com,63000,Aerospace & Defense,Aerospace and Defense,"Waltham, MA",870 Winter St.,Waltham,MA,...,Chairman & Chief Executive Officer,"870 Winter St., Waltham, MA 02451",RTN,Raytheon Company,24069,3.5,2211.0,6.6,30052,10066.0
199,200,Textron,http://www.textron.com,36000,Aerospace & Defense,Aerospace and Defense,"Providence, RI",40 Westminster St.,Providence,RI,...,"Chairman, President & Chief Executive Officer","40 Westminster St., Providence, RI 02903",TXT,Textron Inc.,13788,2.7,962.0,38,15358,5574.0
227,228,Arconic,http://www.arconic.com,41500,Aerospace & Defense,Aerospace and Defense,"New York, NY",390 Park Ave.,New York,NY,...,Interim Chief Executive Officer & Director,"390 Park Ave., New York, NY 10022",ARNC,Arconic Inc.,12394,-45.0,-941.0,6.7,20038,5115.0
272,273,L3 Technologies,http://www.l3t.com,38000,Aerospace & Defense,Aerospace and Defense,"New York, NY",600 Third Ave.,New York,NY,...,Chairman & Chief Executive Officer,"600 Third Ave., New York, NY 10016",LLL,"L3 Technologies, Inc.",10597,-8.3,710.0,19.4,11865,4553.0
379,380,Huntington Ingalls Industries,http://www.huntingtoningalls.com%20,37000,Aerospace & Defense,Aerospace and Defense,"Newport News, VA",4101 Washington Ave.,Newport News,VA,...,"President, Chief Executive Officer & Director","4101 Washington Ave., Newport News, VA 23607",HII,"Huntington Ingalls Industries, Inc.",7068,0.7,573.0,41.8,6352,1653.0
392,393,Spirit AeroSystems Holdings,http://www.spiritaero.com,14400,Aerospace & Defense,Aerospace and Defense,"Wichita, KS",3801 S. Oliver St.,Wichita,KS,...,"President, Chief Executive Officer & Director","3801 S. Oliver St., Wichita, KS 67210",SPR,"Spirit AeroSystems Holdings, Inc.",6793,2.2,469.7,-40.4,5405,1928.0
491,492,Rockwell Collins,http://www.rockwellcollins.com,19000,Aerospace & Defense,Aerospace and Defense,"Cedar Rapids, IA",400 Collins Rd. N.E.,Cedar Rapids,IA,...,"Chairman, President & Chief Executive Officer","400 Collins Rd. N.E., Cedar Rapids, IA 52498",COL,"Rockwell Collins, Inc.",5259,-0.1,728.0,6.1,7707,2078.0